- name: Deploy LND
  include_role:
    name: k8s/utils/kubectl-create-or-replace
  vars:
    controller_kind: deploy
    controller_name: "{{bitcoin_lnd_app_name}}"
    controller_template: lnd.yaml.j2
