- name: Deploy bitcoin node
  include_role:
    name: k8s/utils/kubectl-create-or-replace
  vars:
    controller_kind: deploy
    controller_name: "{{bitcoin_bitcoind_app_name}}"
    controller_template: bitcoind.yaml.j2
